on:
  push:
    branches:
      - main
jobs:
  automatic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: |
          VERSION=$(jq -r '.version' package.json)
          TITLE="Release v$VERSION"  # Customize title format if needed
          echo "TITLE=$TITLE" >> $GITHUB_STATE
      - name: Peek title
        run: |
          echo "Title is"
          echo ${{GITHUB_STATE.TITLE}}
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          automatic_release_tag: stable
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: ${{GITHUB_STATE.TITLE}
