on:
  push:
    branches:
      - main

jobs:
  automatic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get-version
        run: |
          VERSION=$(jq -r '.version' package.json)
          TITLE="Release v$VERSION"  # Customize title format if needed
          echo "title=$TITLE" >> $GITHUB_OUTPUT
      - name: Peek title
        run: |
          echo "Title is"
          echo ${{steps.get-version.outputs.title}}
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          automatic_release_tag: stable
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: ${{steps.get-version.outputs.title}}
