on:
  push:
    branches:
      - main
jobs:
  automatic-release:
    runs-on: ubuntu-latest
    steps:
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        automatic_release_tag: stable
